Add warmPrefixTarget and enablePrefixDelegation support to vpc cni op…
pulumi/pulumi-eks pull request #618
Opened 2021-09-07 09:02 UTC by davidroth

See: https://github.com/pulumi/pulumi-eks/issues/608

NodeJs support only for now. Let me know if the other languages are required for the MR to be accepted.

2021-10-13 22:38 UTC, leezen commented
@davidroth Sorry for not replying sooner. Since this is a multi-language component, you should be able to automatically generate the appropriate SDKs. Note that the schema is actually generated from a Go program (see `provider/cmd/pulumi-gen-eks`) so if you modify that along with modifying the underlying provider itself (as you've done w/ the .ts files), then you should be able to run `make build` to generate the other language SDKs as part of this PR.

2021-11-09 13:33 UTC, davidroth commented
@leezen Ok, I updated `provider/cmd/pulumi-gen-eks\main.go` and generated the files for the `dotnet` `python` and `go` providers.
Please let me know if anything is missing.

2021-11-10 08:31 UTC, davidroth commented
Rebased, fixed linting error + updated changelog.

2021-11-11 11:50 UTC, davidroth commented
@lblackstone Any chance of somebody reviewing this so that it can go into the 0.36 release?

2021-11-11 15:58 UTC, lblackstone commented
> @lblackstone Any chance of somebody reviewing this so that it can go into the 0.36 release?

Thanks for the PR! I just added it to our review queue so we'll take a look shortly.

2021-11-11 17:20 UTC, lblackstone requested changes
Looks good overall

2021-11-11 17:20 UTC, lblackstone commented on nodejs/eks/cmd/provider/cni.ts
> +        env.push({name: "ENABLE_PREFIX_DELEGATION ", value: args.enablePrefixDelegation.toString()});
I think you need to handle the boolean value instead.
```suggestion
        env.push({name: "ENABLE_PREFIX_DELEGATION ", value: args.enablePrefixDelegation ? "true" : "false"});
```

2021-11-11 17:21 UTC, lblackstone commented
/run-acceptance-tests

2021-11-11 18:51 UTC, lblackstone approved these changes

2021-11-11 18:52 UTC, merged