change ec2 dnsSuffix principal in policy
pulumi/pulumi-eks pull request #801
Opened 2022-10-25 07:01 UTC by liutao-samsung

### Proposed changes

IAM principal in policy may be different in different aws partition.
https://github.com/weaveworks/eksctl/blob/main/pkg/cfn/builder/partition.go#L9

### Related issues (optional)

2022-11-21 10:39 UTC, danielrbradley requested changes
This looks great thanks! 

Just a minor tweak needed to avoid us doing two roundtrips to get the partition information then we'll get this merged

2022-11-21 10:39 UTC, danielrbradley commented on nodejs/eks/cluster.ts
> +    const dnsSuffix = pulumi.output(aws.getPartition({ provider })).dnsSuffix;
We should be able to fetch both in a single call and grab the two values we need.

```suggestion
    const { partition, dnsSuffix } = pulumi.output(aws.getPartition({ provider }));
```

2022-11-28 11:40 UTC, danielrbradley commented
/run-acceptance-tests

2022-12-02 10:21 UTC, liutao-samsung commented
What should I do next?

2022-12-02 13:51 UTC, liutao-samsung commented
@danielrbradley  Hi ~ , would you kick off  the test again ?

2022-12-02 14:12 UTC, danielrbradley commented
/run-acceptance-tests

2022-12-02 20:18 UTC, danielrbradley commented
I'm afraid we're still getting test failures, though it might still be unrelated to your change.

```
pulumi:pulumi:Stack (example-cluster-p-it-fv-az419-8-cluster-5c222dca):
      error: Running program '/tmp/p-it-fv-az419-8-cluster-5c222dca-2770179391' failed with an unhandled exception:
      TypeError: Cannot read properties of undefined (reading 'data')
          at /home/runner/work/pulumi-eks/pulumi-eks/nodejs/eks/cluster.ts:586:103
          at /home/runner/work/pulumi-eks/pulumi-eks/nodejs/eks/node_modules/@pulumi/output.ts:383:31
          at Generator.next (<anonymous>)
          at /home/runner/work/pulumi-eks/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
          at new Promise (<anonymous>)
          at __awaiter (/home/runner/work/pulumi-eks/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:17:12)
          at applyHelperAsync (/home/runner/work/pulumi-eks/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:236:12)
          at /home/runner/work/pulumi-eks/pulumi-eks/nodejs/eks/node_modules/@pulumi/output.ts:302:65
      error: update failed
```

A brief glance looks like it's related to `clusterCertificateAuthority`. This will probably required a bit more investigation before we get a clean build. Sorry for the slow process. 

cc: @roothorp

2022-12-02 21:54 UTC, roothorp commented
I think this is the issue from #676?

2022-12-06 15:13 UTC, danielrbradley approved these changes

2022-12-06 15:13 UTC, merged